title: Flex
name: "Anushka Trivedi"
markdown: redcarpet
highlighter: true
locale: "en-US"
repository: opheliagame/opheliagame.gitub.io

#jekyll plugin for github metadata 
plugins:
  - "jekyll-github-metadata"