  module.exports = [
  {
    caption: "let's see how I stumble down this track!",
    alt: "क",
    src: "/assets/img/projects/36daysoftype/क.gif",
    ig_url: "https://www.instagram.com/p/CNbwpRLHoc9/",
  },
  {
    caption: "ख is a love story between र and व that is playing out right in front of our eyes and I for one had not noticed until today, had you?",
    alt: "ख",
    src: "/assets/img/projects/36daysoftype/ख.gif",
    ig_url: "https://www.instagram.com/p/CNed2P6n0ac/",
  },
  {
    caption: "सारे के सारे गा मा को लेकर गाते चले",
    alt: "ग",
    src: "/assets/img/projects/36daysoftype/ग.gif",
    ig_url: "https://www.instagram.com/p/CNhde0WHUR_/",
  },
  {
    caption: "घनन घनन",
    alt: "घ",
    src: "/assets/img/projects/36daysoftype/घ.gif",
    ig_url: "https://www.instagram.com/p/CNjzAD_HsCT/",
  },
  {
    caption: "day 5",
    alt: "ङ",
    src: "/assets/img/projects/36daysoftype/ङ.gif",
    ig_url: "https://www.instagram.com/p/CNmuafWHawp/",
  },
  {
    caption: "day 5",
    alt: "ङ",
    src: "/assets/img/projects/36daysoftype/ङ-2.gif",
    ig_url: "https://www.instagram.com/p/CNmuafWHawp/",
  },
  {
    caption: "यहाँ थूकना मना है",
    alt: "च",
    src: "/assets/img/projects/36daysoftype/च.gif",
    ig_url: "https://www.instagram.com/p/CNpJc13nmjW/",
  },
  {
    caption: "छलांग",
    alt: "छ",
    src: "/assets/img/projects/36daysoftype/छ.gif",
    ig_url: "https://www.instagram.com/p/CNsUKxTHmc1/",
  },
  {
    caption: "परछाई",
    alt: "ज",
    src: "/assets/img/projects/36daysoftype/ज.gif",
    ig_url: "https://www.instagram.com/p/CNuEjiWH-TB/",
  },
  {
    caption: "घूम घूम",
    alt: "झ",
    src: "/assets/img/projects/36daysoftype/झ.gif",
    ig_url: "https://www.instagram.com/p/CNx98CGnIYi/",
  },
  {
    caption: "nose ring",
    alt: "ञ",
    src: "/assets/img/projects/36daysoftype/ञ.gif",
    ig_url: "https://www.instagram.com/p/CN0SdDpH246/",
  },
  {
    caption: "I'm afraid I've started incorporating Rajnikanth's style in my work 😂😂",
    alt: "ट",
    src: "/assets/img/projects/36daysoftype/ट.gif",
    ig_url: "https://www.instagram.com/p/CN2nUJOHgjx/",
  },
  {
    caption: "open your mouth hahaha",
    alt: "ठ",
    src: "/assets/img/projects/36daysoftype/ठ.gif",
    ig_url: "https://www.instagram.com/p/CN43_MYHVlL/",
  },
  {
    caption: "oops I did it again",
    alt: "ड",
    src: "/assets/img/projects/36daysoftype/ड.gif",
    ig_url: "https://www.instagram.com/p/CN7rT-sHPgQ/",
  },
  {
    caption: "day 14",
    alt: "ढ",
    src: "/assets/img/projects/36daysoftype/ढ.gif",
    ig_url: "https://www.instagram.com/p/CN-UoUaHLOg/",
  },
  {
    caption: "प प प प पर",
    alt: "ण",
    src: "/assets/img/projects/36daysoftype/ण.gif",
    ig_url: "https://www.instagram.com/p/COBZQhaHI2n/",
  },
  {
    caption: "bucket the kick",
    alt: "त",
    src: "/assets/img/projects/36daysoftype/त.gif",
    ig_url: "https://www.instagram.com/p/COD4U1CnBTb/",
  },
  {
    caption: "in the business of marrying off letters to each other",
    alt: "थ",
    src: "/assets/img/projects/36daysoftype/थ.gif",
    ig_url: "https://www.instagram.com/p/COGDR7HnVfr/",
  },
  {
    caption: "pulling ढ's ear",
    alt: "द",
    src: "/assets/img/projects/36daysoftype/द.gif",
    ig_url: "https://www.instagram.com/p/COI9Ch_Hgox/",
  },
  {
    caption: "pulling ढ's ear",
    alt: "द",
    src: "/assets/img/projects/36daysoftype/द-2.gif",
    ig_url: "https://www.instagram.com/p/COI9Ch_Hgox/",
  },
  {
    caption: "wanted to do a hair twang sort of thing but since that didn't work we'll roll with ध ft. dumbbells",
    alt: "ध",
    src: "/assets/img/projects/36daysoftype/ध.gif",
    ig_url: "https://www.instagram.com/p/COLhZe4nMKJ/",
  },
  {
    caption: "the story continues",
    alt: "न",
    src: "/assets/img/projects/36daysoftype/न.gif",
    ig_url: "https://www.instagram.com/p/COPQCyAn5Je/",
  },
  {
    caption: "top of the hat to ya",
    alt: "प",
    src: "/assets/img/projects/36daysoftype/प.gif",
    ig_url: "https://www.instagram.com/p/COVCZulHECu/",
  },
  {
    caption: "फालतू",
    alt: "फ",
    src: "/assets/img/projects/36daysoftype/फ.gif",
    ig_url: "https://www.instagram.com/p/COZqErAnYj1/",
  },
  {
    caption: "बस",
    alt: "ब",
    src: "/assets/img/projects/36daysoftype/ब.gif",
    ig_url: "https://www.instagram.com/p/COcH2ViHWXl/",
  },
  {
    caption: " मेरे चश्मे कहाँ हैं (;ŏ﹏ŏ) where are my specs",
    alt: "भ",
    src: "/assets/img/projects/36daysoftype/भ.gif",
    ig_url: "https://www.instagram.com/p/COe0pUznHij/",
  },
  {
    caption: "tied together",
    alt: "म",
    src: "/assets/img/projects/36daysoftype/म.gif",
    ig_url: "https://www.instagram.com/p/COh0424nDKy/",
  },
  {
    caption: "yeah this got a bit fantastical",
    alt: "य",
    src: "/assets/img/projects/36daysoftype/य.gif",
    ig_url: "https://www.instagram.com/p/COj4Imfnmyg/",
  },
  {
    caption: "can't rrrroll my tongue",
    alt: "र",
    src: "/assets/img/projects/36daysoftype/र.gif",
    ig_url: "https://www.instagram.com/p/COnOBGfnYiI/",
  },
  {
    caption: "brain tap",
    alt: "ल",
    src: "/assets/img/projects/36daysoftype/ल.gif",
    ig_url: "https://www.instagram.com/p/COso-C6HKS2/",
  },
  {
    caption: "ब removes it's inhibitions once in a while and becomes व xD",
    alt: "व",
    src: "/assets/img/projects/36daysoftype/व.gif",
    ig_url: "https://www.instagram.com/p/COw0-jBntub/",
  },
  {
    caption: "when in doubt string together letters",
    alt: "श",
    src: "/assets/img/projects/36daysoftype/श.gif",
    ig_url: "https://www.instagram.com/p/CO3Bf6PHHbV/",
  },
  {
    caption: "itsy bitsy",
    alt: "ष",
    src: "/assets/img/projects/36daysoftype/ष.gif",
    ig_url: "https://www.instagram.com/p/CO8X1l2HeVr/",
  },
  {
    caption: "ढिलमिल बिंदु | tipping point",
    alt: "स",
    src: "/assets/img/projects/36daysoftype/स.gif",
    ig_url: "https://www.instagram.com/p/CO-jToYHppx/",
  },
  {
    caption: "जुम्मा चुम्मा दे दे (ノ^_^)ノ",
    alt: "ह",
    src: "/assets/img/projects/36daysoftype/ह.gif",
    ig_url: "https://www.instagram.com/p/CPBlv8HHkii/",
  },
  {
    caption: "note, rest \nhoping to clean this up a bit later (-_-メ) and again just immense respect for type designers",
    alt: "क्ष",
    src: "/assets/img/projects/36daysoftype/क्ष.gif",
    ig_url: "https://www.instagram.com/p/CPEQ2DbnC4J/",
  },
  {
    caption: "चोंच • beak",
    alt: "त्र",
    src: "/assets/img/projects/36daysoftype/त्र.gif",
    ig_url: "https://www.instagram.com/p/CPKbZehHt8Z/",
  },
  {
    caption: "curl up ➰",
    alt: "ज्ञ",
    src: "/assets/img/projects/36daysoftype/ज्ञ.gif",
    ig_url: "https://www.instagram.com/p/CPPmmQIHxrY/",
  },
  
  ]